services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && gunicorn habit_tracker.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:7.4.3
    env_file:
      - .env
    ports:
      - '6379:6379'
  celery:
    build: .
    depends_on:
      - redis
    command: celery -A habit_tracker worker -l info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env
networks:
  default:
volumes:
  postgres_data:
  static_volume:
  redis_volume:
