version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0:8000
    environment:
      - DEBUG=True
      - DATABASE_HOST=db
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:16.8
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U myuser']
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  default:

volumes:
  postgres_data:
  static_volume: