# Generated by Django 5.2 on 2025-04-26 18:58

import django.db.models.deletion
from django.db import migrations, models

import habit.validators


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="linked_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habit.habit",
                validators=[habit.validators.validate_related_habit],
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Ежедневно"),
                    (2, "Раз в 2 дня"),
                    (3, "Раз в 3 дня"),
                    (4, "Раз в 4 дня"),
                    (5, "Раз в 5 дней"),
                    (6, "Раз в 6 дней"),
                    (7, "Раз в неделю"),
                ],
                default=1,
                validators=[habit.validators.validate_periodicity],
                verbose_name="Периодичность",
            ),
        ),
    ]
