# Generated by Django 5.2 on 2025-04-23 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='frequency',
        ),
        migrations.AddField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ежедневно'), (2, 'Раз в 2 дня'), (3, 'Раз в 3 дня'), (4, 'Раз в 4 дня'), (5, 'Раз в 5 дней'), (6, 'Раз в 6 дней'), (7, 'Раз в неделю')], default=1, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Время на выполнение (секунды)'),
        ),
    ]
